//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularWebAPIDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORUSERMST
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Address { get; set; }
        public string User_EmailID { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public Nullable<System.DateTime> User_CreatedDateTime { get; set; }
        public Nullable<int> User_CreatedByUserID { get; set; }
    }
}
